---
- name: Configure NFS Mount
  hosts: all
  become: yes
  tasks:
    - name: Gather OS facts
      setup:
        gather_subset:
          - '!all'
          - 'pkg_mgr'

    - name: Install NFS utils for RedHat/CentOS/Fedora
      dnf:
        name: nfs-utils
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Install NFS utils for older RedHat/CentOS
      yum:
        name: nfs-utils
        state: present
      when: ansible_pkg_mgr == 'yum'

    - name: Install NFS utils for Debian/Ubuntu
      apt:
        name: nfs-common
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Create /eic directory
      file:
        path: /eic
        state: directory
        mode: '0777'
        owner: nobody
        group: eic-con_users

    - name: Create mount file
      copy:
        dest: /etc/systemd/system/eic.mount
        content: |
          [Unit]
          Description=NFS Mount
          [Mount]
          What=devnas01.eic.bnl.gov:/mnt/nfsstore/pool1
          Where=/eic
          Type=nfs
          Options=rw,sync,hard,intr,nosuid
          [Install]
          WantedBy=multi-user.target

    - name: Create automount file
      copy:
        dest: /etc/systemd/system/eic.automount
        content: |
          [Unit]
          Description=NFS AutoMount -- eic
          [Automount]
          Where=/eic
          [Install]
          WantedBy=multi-user.target

    - name: Enable and start eic.automount
      systemd:
        name: eic.automount
        enabled: yes
        state: started
        daemon_reload: yes
