---

# - name: Install Anaconda from Environment
#   import_tasks: install_env.yml

- name: Install Anaconda from Archive
  import_tasks: install_archive.yml

- name: Install Pip Configuration
  import_tasks: configure_pip.yml