---
- hosts: all
  become: true
  roles:
    - role: org.phoebus.phoebus_dependencies
    - role: org.phoebus.phoebus_services_aa
  vars:
    aa_mysql_server: "demo02.eic.bnl.gov"
    aa_java_opts_engine: "-XX:+UseG1GC -Xmx1G -Xms256M -ea"
    aa_java_opts_retrieval: "-XX:+UseG1GC -Xmx1G -Xms256M -ea"
    aa_java_opts_etl: "-XX:+UseG1GC -Xmx512M -Xms256M -ea"
    aa_java_opts_mgmt: "-XX:+UseG1GC -Xmx512M -Xms256M -ea"

