---
- hosts: all
  roles:
    - role: '/opt/ansible/ansible-epics-tools/roles/epics_tools_libs_jvm'
    - role: '/opt/ansible/ansible-epics-tools/roles/epics_tools_services_elastic'
    - role: '/opt/ansible/ansible-epics-tools/roles/epics_tools_services_kafka'
    - role: '/opt/ansible/ansible-epics-tools/roles/cs_studio_phoebus'
    - role: '/opt/ansible/ansible-epics-tools/roles/epics_tools_services_phoebus_alarm'
  vars:
    
    epics_services_account: eicuser
    beamline_name: "eic"
    beamline_id: "00"   
    alarm_config: "EIC"
    

