---
- hosts: all
  become: true
  roles:
    - role: org.phoebus.phoebus_dependencies
    - role: org.phoebus.phoebus_services_elasticsearch
    - role: org.phoebus.phoebus_services_kafka
    - role: org.phoebus.phoebus_tools
    - role: org.phoebus.phoebus_services_phoebus_alarm
  vars:
    phoebus_tools_owner: eicuser
    phoebus_services_phoebus_alarm_config: EIC

