---
- hosts: all
  roles:
    - role: '/opt/ansible/ansible-eic-epics-tools/roles/epics_tools_libs_jvm'
    - role: '/opt/ansible/ansible-eic-epics-tools/roles/epics_tools_services_elastic'
    - role: '/opt/ansible/ansible-eic-epics-tools/roles/cs_studio_phoebus'
    - role: '/opt/ansible/ansible-eic-epics-tools/roles/epics_tools_services_cf'
    - role: '/opt/ansible/ansible-eic-epics-tools/roles/epics_tools_services_recceiver'
  vars:    
    epics_services_account: eicuser
    beamline_name: "eic"
    beamline_id: "00"
    

