localhost

[workstations]
demo01.eic.bnl.gov
demo02.eic.bnl.gov
demo03.eic.bnl.gov
demo04.eic.bnl.gov
demo05.eic.bnl.gov
demo06.eic.bnl.gov
eicchat.bnl.gov
alarmdemo.eic.bnl.gov
#fpgadev.eic.bnl.gov

[alarm-server]
demo01.eic.bnl.gov

[alarm-demo]
alarmdemo.eic.bnl.gov

[archiver]
demo01.eic.bnl.gov

[olog]
demo03.eic.bnl.gov

[channelfinder]
demo02.eic.bnl.gov

[save-restore]
demo02.eic.bnl.gov

[pheobus-jen]
demo06.eic.bnl.gov

[kyle-test]
demo06.eic.bnl.gov

[eicchatdev]
eicchat.bnl.gov

[fpgadev]
fpgadev.eic.bnl.gov

[hcoatingdev01]
hcoatingdev01.eic.bnl.gov
