localhost

[workstations]
demo01.eic.bnl.gov #130.199.97.30 
demo02.eic.bnl.gov #130.199.97.36 
demo03.eic.bnl.gov
demo04.eic.bnl.gov

[alarm-server]
demo01.eic.bnl.gov

[archiver]
demo01.eic.bnl.gov

[olog]
demo02.eic.bnl.gov

[channelfinder]
demo02.eic.bnl.gov

[save-restore]
demo02.eic.bnl.gov

[python]
demo04.eic.bnl.gov