---
- hosts: all
  roles:
    - role: '/opt/ansible/ansible-eic-epics-tools/roles/epics_tools_libs_jvm'
    - role: '/opt/ansible/ansible-eic-epics-tools/roles/cs_studio_phoebus'
    - role: '/opt/ansible/ansible-eic/roles/cs_studio_resources'
  vars:
    epics_services_account: eicuser
    beamline_name: "eic"
    beamline_id: "00"
    phoebus_pref: "/opt/eic-phoebus-resources/preferences/preferences/pref.ini"
    phoebus_owner: "eicuser"
    cs_studio_resources_config:
      repo: "https://github.com/eicorg/eic-phoebus-resources.git"
      version: "main"
      basedir: /opt/eic-phoebus-resources/preferences
      configdir: /opt/eic-phoebus-resources/configuration
      user: eicuser
