---
- hosts: all
  roles:
    - role: '/opt/ansible/ansible-epics-tools/roles/cs_studio_phoebus'
    - role: '/opt/ansible/ansible-epics-tools/roles/epics_tools_services_save_restore'
  vars:    
    epics_services_account: epics-services
    beamline_name: "training"
    beamline_id: "00"
    

