---
- hosts: all
  become: true
  roles:
    - role: org.phoebus.phoebus_dependencies
    - role: org.phoebus.phoebus_services_elasticsearch
    - role: org.phoebus.phoebus_tools
    - role: org.phoebus.phoebus_services_save_restore
  vars:
    phoebus_tools_owner: eicuser
