---
epics_bundle_url: "https://github.com/eicorg/epics-rpm-config/releases/download/eic-7.0.10_1.0.0-2/epics-bundle-7.0.10_1.0.0-2.el9.x86_64.rpm"
epics_bundle_filename: ""
epics_bundle_work_dir: /var/tmp/epics-bundle
epics_bundle_force_download: false
epics_bundle_download_timeout: 60
epics_bundle_disable_gpg_check: true
epics_bundle_cleanup: false
